export const SHOP_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const SHOP_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const SHOP_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const SHOP_LOGOUT = 'USER_LOGOUT'

export const SHOP_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const SHOP_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const SHOP_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const SHOP_REGISTER_RESET = 'USER_REGISTER_RESET'
